# Generated by Django 5.2.4 on 2025-07-25 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauthapp', '0002_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=datetime.datetime(2025, 7, 25, 7, 36, 52, 477365, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
